image: tiangolo/docker-with-compose

stages:
  - test
  - build
  
test:
  stage: test
  services:
    - name: docker:dind
      alias: docker
  script:
    - echo "chumz_website"
    
build:
  stage: build
  services:
    - name: docker:dind
      alias: docker
  script:
  
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose config
    - docker-compose build
    - docker-compose push "${CI_REGISTRY_IMAGE}":"${CI_COMMIT_SHORT_SHA}";
    
  only : 
    - master
 

