version: '3.7'

services:

  chumz_website:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - '80'